---
#local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portal?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: OntactRoot2022#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
server:
  port: 8080