---
#local
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/portal?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: local
server:
  port: 8080

jwt:
  accessTokenKey: leejaeiktest
  refreshTokenKey: leejaeikretest
  time:
    accessToken : 600000
    refreshToken : 3600000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

security:
  getUrlList:
    - /targets
    - /actuator/**
    - /v1/**
    - /user
    - /user/all
  postUrlList:
    - /v1/**
    - /user
    - /user/login
---
